version: "3.9"
services:
  api:
    container_name: DiagnosticsApi
    build: .
    restart: always
    expose:
      - '80'
    ports:
      - "80:80"  # http

  interface:
    container_name: DiagnosticsInterface
    build: /DiagnosticsFrontEnd
    restart: always
    expose:
     - '4200'
    ports:
     - "4200:4200"