version: "3.9"
services:
  api:
    container_name: Api
    build: .
    expose:
      - '80'
    ports:
      - "80:80"  # http

  interface:
    container_name: Interface
    build: /DiagnosticsFrontEnd
    expose:
     - '4200'
    ports:
     - "4200:4200"