//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Archer.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IArcherListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ArcherBaseListener : IArcherListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] ArcherParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] ArcherParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>modelStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelStatement([NotNull] ArcherParser.ModelStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>modelStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelStatement([NotNull] ArcherParser.ModelStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>relationshipStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationshipStatement([NotNull] ArcherParser.RelationshipStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>relationshipStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationshipStatement([NotNull] ArcherParser.RelationshipStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>variableDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationStatement([NotNull] ArcherParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>variableDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationStatement([NotNull] ArcherParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>constraintStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstraintStatement([NotNull] ArcherParser.ConstraintStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>constraintStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstraintStatement([NotNull] ArcherParser.ConstraintStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>conditionStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionStatement([NotNull] ArcherParser.ConditionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>conditionStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionStatement([NotNull] ArcherParser.ConditionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lowerBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLowerBoundStatement([NotNull] ArcherParser.LowerBoundStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lowerBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLowerBoundStatement([NotNull] ArcherParser.LowerBoundStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>upperBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpperBoundStatement([NotNull] ArcherParser.UpperBoundStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>upperBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpperBoundStatement([NotNull] ArcherParser.UpperBoundStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDeclarationStatement([NotNull] ArcherParser.FuncDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDeclarationStatement([NotNull] ArcherParser.FuncDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>includeStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeStatement([NotNull] ArcherParser.IncludeStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>includeStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeStatement([NotNull] ArcherParser.IncludeStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>objectiveStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectiveStatement([NotNull] ArcherParser.ObjectiveStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>objectiveStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectiveStatement([NotNull] ArcherParser.ObjectiveStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>commentStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentStatement([NotNull] ArcherParser.CommentStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>commentStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentStatement([NotNull] ArcherParser.CommentStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.typeDeclr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclr([NotNull] ArcherParser.TypeDeclrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.typeDeclr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclr([NotNull] ArcherParser.TypeDeclrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.objectiveDeclr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectiveDeclr([NotNull] ArcherParser.ObjectiveDeclrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.objectiveDeclr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectiveDeclr([NotNull] ArcherParser.ObjectiveDeclrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] ArcherParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] ArcherParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdList([NotNull] ArcherParser.IdListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdList([NotNull] ArcherParser.IdListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcArgExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncArgExpr([NotNull] ArcherParser.FuncArgExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcArgExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncArgExpr([NotNull] ArcherParser.FuncArgExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueExpr([NotNull] ArcherParser.ValueExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueExpr([NotNull] ArcherParser.ValueExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExpr([NotNull] ArcherParser.AddSubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExpr([NotNull] ArcherParser.AddSubExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>listComprExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListComprExpr([NotNull] ArcherParser.ListComprExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>listComprExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListComprExpr([NotNull] ArcherParser.ListComprExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCallExpr([NotNull] ArcherParser.FuncCallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCallExpr([NotNull] ArcherParser.FuncCallExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>mulDivExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExpr([NotNull] ArcherParser.MulDivExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mulDivExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExpr([NotNull] ArcherParser.MulDivExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>equalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualBinaryExpr([NotNull] ArcherParser.EqualBinaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>equalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualBinaryExpr([NotNull] ArcherParser.EqualBinaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>logicalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalBinaryExpr([NotNull] ArcherParser.LogicalBinaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>logicalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalBinaryExpr([NotNull] ArcherParser.LogicalBinaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.cardinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardinExpr([NotNull] ArcherParser.CardinExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.cardinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardinExpr([NotNull] ArcherParser.CardinExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] ArcherParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] ArcherParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.mulDivExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExprOp([NotNull] ArcherParser.MulDivExprOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.mulDivExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExprOp([NotNull] ArcherParser.MulDivExprOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.addSubExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExprOp([NotNull] ArcherParser.AddSubExprOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.addSubExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExprOp([NotNull] ArcherParser.AddSubExprOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.equalExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualExprOp([NotNull] ArcherParser.EqualExprOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.equalExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualExprOp([NotNull] ArcherParser.EqualExprOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.logicalExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExprOp([NotNull] ArcherParser.LogicalExprOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.logicalExprOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExprOp([NotNull] ArcherParser.LogicalExprOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.propExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropExpr([NotNull] ArcherParser.PropExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.propExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropExpr([NotNull] ArcherParser.PropExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObj([NotNull] ArcherParser.ObjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObj([NotNull] ArcherParser.ObjContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] ArcherParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] ArcherParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] ArcherParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] ArcherParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.primitiveValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveValue([NotNull] ArcherParser.PrimitiveValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.primitiveValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveValue([NotNull] ArcherParser.PrimitiveValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] ArcherParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] ArcherParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.listCompr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListCompr([NotNull] ArcherParser.ListComprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.listCompr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListCompr([NotNull] ArcherParser.ListComprContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
