//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Archer.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ArcherParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IArcherVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] ArcherParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modelStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelStatement([NotNull] ArcherParser.ModelStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>relationshipStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipStatement([NotNull] ArcherParser.RelationshipStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarationStatement([NotNull] ArcherParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>constraintStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraintStatement([NotNull] ArcherParser.ConstraintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>conditionStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionStatement([NotNull] ArcherParser.ConditionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lowerBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLowerBoundStatement([NotNull] ArcherParser.LowerBoundStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>upperBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpperBoundStatement([NotNull] ArcherParser.UpperBoundStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDeclarationStatement([NotNull] ArcherParser.FuncDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>includeStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncludeStatement([NotNull] ArcherParser.IncludeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>objectiveStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectiveStatement([NotNull] ArcherParser.ObjectiveStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>commentStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentStatement([NotNull] ArcherParser.CommentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.typeDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDeclr([NotNull] ArcherParser.TypeDeclrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.objectiveDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectiveDeclr([NotNull] ArcherParser.ObjectiveDeclrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] ArcherParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdList([NotNull] ArcherParser.IdListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcArgExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncArgExpr([NotNull] ArcherParser.FuncArgExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valueExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpr([NotNull] ArcherParser.ValueExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSubExpr([NotNull] ArcherParser.AddSubExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listComprExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListComprExpr([NotNull] ArcherParser.ListComprExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallExpr([NotNull] ArcherParser.FuncCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>mulDivExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivExpr([NotNull] ArcherParser.MulDivExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>equalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualBinaryExpr([NotNull] ArcherParser.EqualBinaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logicalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalBinaryExpr([NotNull] ArcherParser.LogicalBinaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.cardinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCardinExpr([NotNull] ArcherParser.CardinExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] ArcherParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.mulDivExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivExprOp([NotNull] ArcherParser.MulDivExprOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.addSubExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSubExprOp([NotNull] ArcherParser.AddSubExprOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.equalExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualExprOp([NotNull] ArcherParser.EqualExprOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.logicalExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExprOp([NotNull] ArcherParser.LogicalExprOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.propExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropExpr([NotNull] ArcherParser.PropExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObj([NotNull] ArcherParser.ObjContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] ArcherParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] ArcherParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.primitiveValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveValue([NotNull] ArcherParser.PrimitiveValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] ArcherParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArcherParser.listCompr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListCompr([NotNull] ArcherParser.ListComprContext context);
}
