//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Archer.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public partial class ArcherParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, ID=27, STRING=28, NUMBER=29, BOOLEAN=30, COMMENT=31, 
		MODIFIER=32, KEY=33, MUL=34, DIV=35, MIN=36, ADD=37, GREATERTHAN=38, LESSTHAN=39, 
		GREATERTHAN_E=40, LESSTHAN_E=41, EQUALS=42, AND=43, OR=44, WS=45;
	public const int
		RULE_prog = 0, RULE_stat = 1, RULE_typeDeclr = 2, RULE_objectiveDeclr = 3, 
		RULE_paramList = 4, RULE_idList = 5, RULE_expr = 6, RULE_cardinExpr = 7, 
		RULE_funcCall = 8, RULE_mulDivExprOp = 9, RULE_addSubExprOp = 10, RULE_equalExprOp = 11, 
		RULE_logicalExprOp = 12, RULE_propExpr = 13, RULE_obj = 14, RULE_pair = 15, 
		RULE_value = 16, RULE_primitiveValue = 17, RULE_array = 18, RULE_listCompr = 19;
	public static readonly string[] ruleNames = {
		"prog", "stat", "typeDeclr", "objectiveDeclr", "paramList", "idList", 
		"expr", "cardinExpr", "funcCall", "mulDivExprOp", "addSubExprOp", "equalExprOp", 
		"logicalExprOp", "propExpr", "obj", "pair", "value", "primitiveValue", 
		"array", "listCompr"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'model'", "'{'", "'}'", "'->'", "'constraint'", "'condition'", 
		"'='", "'lower_bound'", "'upper_bound'", "'func'", "'('", "','", "')'", 
		"'=>'", "'#include'", "'int'", "'float'", "'minimize'", "'maximize'", 
		"':'", "'.'", "'['", "']'", "'for'", "'in'", null, null, null, null, null, 
		null, null, "'*'", "'/'", "'-'", "'+'", "'>'", "'<'", "'>='", "'<='", 
		null, "'&&'", "'||'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "ID", "STRING", "NUMBER", "BOOLEAN", "COMMENT", "MODIFIER", 
		"KEY", "MUL", "DIV", "MIN", "ADD", "GREATERTHAN", "LESSTHAN", "GREATERTHAN_E", 
		"LESSTHAN_E", "EQUALS", "AND", "OR", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Archer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ArcherParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ArcherParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ArcherParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(ArcherParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatContext[] stat() {
			return GetRuleContexts<StatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatContext stat(int i) {
			return GetRuleContext<StatContext>(i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 40;
				stat();
				State = 42;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__0) {
					{
					State = 41;
					Match(T__0);
					}
				}

				}
				}
				State = 46;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__5) | (1L << T__6) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << ID) | (1L << COMMENT))) != 0) );
			State = 48;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatContext : ParserRuleContext {
		public StatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat; } }
	 
		public StatContext() { }
		public virtual void CopyFrom(StatContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CommentStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(ArcherParser.COMMENT, 0); }
		public CommentStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterCommentStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitCommentStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommentStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ConstraintStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ConstraintStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterConstraintStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitConstraintStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstraintStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UpperBoundStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ArcherParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public UpperBoundStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterUpperBoundStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitUpperBoundStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUpperBoundStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ModelStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ArcherParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdListContext idList() {
			return GetRuleContext<IdListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatContext[] stat() {
			return GetRuleContexts<StatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatContext stat(int i) {
			return GetRuleContext<StatContext>(i);
		}
		public ModelStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterModelStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitModelStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModelStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LowerBoundStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ArcherParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public LowerBoundStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterLowerBoundStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitLowerBoundStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLowerBoundStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IncludeStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(ArcherParser.STRING, 0); }
		public IncludeStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterIncludeStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitIncludeStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIncludeStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VariableDeclarationStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ArcherParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeDeclrContext typeDeclr() {
			return GetRuleContext<TypeDeclrContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjContext obj() {
			return GetRuleContext<ObjContext>(0);
		}
		public VariableDeclarationStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterVariableDeclarationStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitVariableDeclarationStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclarationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncDeclarationStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] KEY() { return GetTokens(ArcherParser.KEY); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY(int i) {
			return GetToken(ArcherParser.KEY, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public FuncDeclarationStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterFuncDeclarationStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitFuncDeclarationStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncDeclarationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ObjectiveStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ObjectiveDeclrContext objectiveDeclr() {
			return GetRuleContext<ObjectiveDeclrContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ObjectiveStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterObjectiveStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitObjectiveStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjectiveStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RelationshipStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(ArcherParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(ArcherParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MIN() { return GetToken(ArcherParser.MIN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(ArcherParser.KEY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CardinExprContext cardinExpr() {
			return GetRuleContext<CardinExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjContext obj() {
			return GetRuleContext<ObjContext>(0);
		}
		public RelationshipStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterRelationshipStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitRelationshipStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ConditionStatementContext : StatContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ArcherParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ConditionStatementContext(StatContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterConditionStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitConditionStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConditionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatContext stat() {
		StatContext _localctx = new StatContext(Context, State);
		EnterRule(_localctx, 2, RULE_stat);
		int _la;
		try {
			State = 126;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				_localctx = new ModelStatementContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 50;
				Match(T__1);
				State = 51;
				Match(ID);
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__20) {
					{
					State = 52;
					idList();
					}
				}

				State = 55;
				Match(T__2);
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 56;
					stat();
					State = 58;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==T__0) {
						{
						State = 57;
						Match(T__0);
						}
					}

					}
					}
					State = 62;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__5) | (1L << T__6) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << ID) | (1L << COMMENT))) != 0) );
				State = 64;
				Match(T__3);
				}
				break;
			case 2:
				_localctx = new RelationshipStatementContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 66;
				Match(ID);
				State = 67;
				Match(MIN);
				State = 68;
				Match(KEY);
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__11) {
					{
					State = 69;
					cardinExpr();
					}
				}

				State = 72;
				Match(T__4);
				State = 73;
				Match(ID);
				State = 75;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__2) {
					{
					State = 74;
					obj();
					}
				}

				}
				break;
			case 3:
				_localctx = new VariableDeclarationStatementContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__16 || _la==T__17) {
					{
					State = 77;
					typeDeclr();
					}
				}

				State = 80;
				Match(ID);
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__2) {
					{
					State = 81;
					obj();
					}
				}

				}
				break;
			case 4:
				_localctx = new ConstraintStatementContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 84;
				Match(T__5);
				State = 85;
				expr(0);
				}
				break;
			case 5:
				_localctx = new ConditionStatementContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 86;
				Match(T__6);
				State = 87;
				Match(ID);
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__7) {
					{
					State = 88;
					Match(T__7);
					}
				}

				State = 91;
				expr(0);
				}
				break;
			case 6:
				_localctx = new LowerBoundStatementContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 92;
				Match(T__8);
				State = 93;
				Match(ID);
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__7) {
					{
					State = 94;
					Match(T__7);
					}
				}

				State = 97;
				expr(0);
				}
				break;
			case 7:
				_localctx = new UpperBoundStatementContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 98;
				Match(T__9);
				State = 99;
				Match(ID);
				State = 101;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__7) {
					{
					State = 100;
					Match(T__7);
					}
				}

				State = 103;
				expr(0);
				}
				break;
			case 8:
				_localctx = new FuncDeclarationStatementContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 104;
				Match(T__10);
				State = 105;
				Match(KEY);
				State = 106;
				Match(T__11);
				State = 115;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==KEY) {
					{
					State = 107;
					Match(KEY);
					State = 112;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__12) {
						{
						{
						State = 108;
						Match(T__12);
						State = 109;
						Match(KEY);
						}
						}
						State = 114;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 117;
				Match(T__13);
				State = 118;
				Match(T__14);
				State = 119;
				expr(0);
				}
				break;
			case 9:
				_localctx = new IncludeStatementContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 120;
				Match(T__15);
				State = 121;
				Match(STRING);
				}
				break;
			case 10:
				_localctx = new ObjectiveStatementContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 122;
				objectiveDeclr();
				State = 123;
				expr(0);
				}
				break;
			case 11:
				_localctx = new CommentStatementContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 125;
				Match(COMMENT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeDeclrContext : ParserRuleContext {
		public TypeDeclrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeDeclr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterTypeDeclr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitTypeDeclr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDeclr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeDeclrContext typeDeclr() {
		TypeDeclrContext _localctx = new TypeDeclrContext(Context, State);
		EnterRule(_localctx, 4, RULE_typeDeclr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			_la = TokenStream.LA(1);
			if ( !(_la==T__16 || _la==T__17) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectiveDeclrContext : ParserRuleContext {
		public ObjectiveDeclrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objectiveDeclr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterObjectiveDeclr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitObjectiveDeclr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjectiveDeclr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectiveDeclrContext objectiveDeclr() {
		ObjectiveDeclrContext _localctx = new ObjectiveDeclrContext(Context, State);
		EnterRule(_localctx, 6, RULE_objectiveDeclr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			_la = TokenStream.LA(1);
			if ( !(_la==T__18 || _la==T__19) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ParamListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_paramList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterParamList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitParamList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParamList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParamListContext paramList() {
		ParamListContext _localctx = new ParamListContext(Context, State);
		EnterRule(_localctx, 8, RULE_paramList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			expr(0);
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__12) {
				{
				{
				State = 133;
				Match(T__12);
				State = 134;
				expr(0);
				}
				}
				State = 139;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(ArcherParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(ArcherParser.ID, i);
		}
		public IdListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterIdList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitIdList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdListContext idList() {
		IdListContext _localctx = new IdListContext(Context, State);
		EnterRule(_localctx, 10, RULE_idList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140;
			Match(T__20);
			State = 141;
			Match(ID);
			State = 146;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__12) {
				{
				{
				State = 142;
				Match(T__12);
				State = 143;
				Match(ID);
				}
				}
				State = 148;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FuncArgExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(ArcherParser.KEY, 0); }
		public FuncArgExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterFuncArgExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitFuncArgExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncArgExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ValueExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public PropExprContext propExpr() {
			return GetRuleContext<PropExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ValueExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterValueExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitValueExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValueExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AddSubExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddSubExprOpContext addSubExprOp() {
			return GetRuleContext<AddSubExprOpContext>(0);
		}
		public AddSubExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterAddSubExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitAddSubExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddSubExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ListComprExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ListComprContext listCompr() {
			return GetRuleContext<ListComprContext>(0);
		}
		public ListComprExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterListComprExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitListComprExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListComprExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncCallExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public FuncCallContext funcCall() {
			return GetRuleContext<FuncCallContext>(0);
		}
		public FuncCallExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterFuncCallExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitFuncCallExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncCallExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MulDivExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulDivExprOpContext mulDivExprOp() {
			return GetRuleContext<MulDivExprOpContext>(0);
		}
		public MulDivExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterMulDivExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitMulDivExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMulDivExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EqualBinaryExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EqualExprOpContext equalExprOp() {
			return GetRuleContext<EqualExprOpContext>(0);
		}
		public EqualBinaryExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterEqualBinaryExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitEqualBinaryExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqualBinaryExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LogicalBinaryExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprOpContext logicalExprOp() {
			return GetRuleContext<LogicalExprOpContext>(0);
		}
		public LogicalBinaryExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterLogicalBinaryExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitLogicalBinaryExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalBinaryExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 12;
		EnterRecursionRule(_localctx, 12, RULE_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 157;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				{
				_localctx = new FuncArgExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 150;
				Match(KEY);
				}
				break;
			case 2:
				{
				_localctx = new ValueExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 153;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case ID:
					{
					State = 151;
					propExpr();
					}
					break;
				case T__2:
				case T__22:
				case STRING:
				case NUMBER:
				case BOOLEAN:
					{
					State = 152;
					value();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 3:
				{
				_localctx = new FuncCallExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 155;
				funcCall();
				}
				break;
			case 4:
				{
				_localctx = new ListComprExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 156;
				listCompr();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 177;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 175;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
					case 1:
						{
						_localctx = new MulDivExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 159;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 160;
						mulDivExprOp();
						State = 161;
						expr(9);
						}
						break;
					case 2:
						{
						_localctx = new AddSubExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 163;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 164;
						addSubExprOp();
						State = 165;
						expr(8);
						}
						break;
					case 3:
						{
						_localctx = new EqualBinaryExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 167;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 168;
						equalExprOp();
						State = 169;
						expr(6);
						}
						break;
					case 4:
						{
						_localctx = new LogicalBinaryExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 171;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 172;
						logicalExprOp();
						State = 173;
						expr(5);
						}
						break;
					}
					} 
				}
				State = 179;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class CardinExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER() { return GetTokens(ArcherParser.NUMBER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER(int i) {
			return GetToken(ArcherParser.NUMBER, i);
		}
		public CardinExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cardinExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterCardinExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitCardinExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCardinExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CardinExprContext cardinExpr() {
		CardinExprContext _localctx = new CardinExprContext(Context, State);
		EnterRule(_localctx, 14, RULE_cardinExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 180;
			Match(T__11);
			State = 181;
			Match(NUMBER);
			State = 182;
			Match(T__12);
			State = 184;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NUMBER) {
				{
				State = 183;
				Match(NUMBER);
				}
			}

			State = 186;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FuncCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(ArcherParser.KEY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParamListContext paramList() {
			return GetRuleContext<ParamListContext>(0);
		}
		public FuncCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funcCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterFuncCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitFuncCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FuncCallContext funcCall() {
		FuncCallContext _localctx = new FuncCallContext(Context, State);
		EnterRule(_localctx, 16, RULE_funcCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			Match(KEY);
			State = 189;
			Match(T__11);
			State = 191;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__2) | (1L << T__22) | (1L << ID) | (1L << STRING) | (1L << NUMBER) | (1L << BOOLEAN) | (1L << KEY))) != 0)) {
				{
				State = 190;
				paramList();
				}
			}

			State = 193;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulDivExprOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL() { return GetToken(ArcherParser.MUL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(ArcherParser.DIV, 0); }
		public MulDivExprOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mulDivExprOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterMulDivExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitMulDivExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMulDivExprOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MulDivExprOpContext mulDivExprOp() {
		MulDivExprOpContext _localctx = new MulDivExprOpContext(Context, State);
		EnterRule(_localctx, 18, RULE_mulDivExprOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195;
			_la = TokenStream.LA(1);
			if ( !(_la==MUL || _la==DIV) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddSubExprOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADD() { return GetToken(ArcherParser.ADD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MIN() { return GetToken(ArcherParser.MIN, 0); }
		public AddSubExprOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addSubExprOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterAddSubExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitAddSubExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddSubExprOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AddSubExprOpContext addSubExprOp() {
		AddSubExprOpContext _localctx = new AddSubExprOpContext(Context, State);
		EnterRule(_localctx, 20, RULE_addSubExprOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197;
			_la = TokenStream.LA(1);
			if ( !(_la==MIN || _la==ADD) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EqualExprOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATERTHAN() { return GetToken(ArcherParser.GREATERTHAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESSTHAN() { return GetToken(ArcherParser.LESSTHAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESSTHAN_E() { return GetToken(ArcherParser.LESSTHAN_E, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATERTHAN_E() { return GetToken(ArcherParser.GREATERTHAN_E, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(ArcherParser.EQUALS, 0); }
		public EqualExprOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equalExprOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterEqualExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitEqualExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqualExprOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EqualExprOpContext equalExprOp() {
		EqualExprOpContext _localctx = new EqualExprOpContext(Context, State);
		EnterRule(_localctx, 22, RULE_equalExprOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 199;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GREATERTHAN) | (1L << LESSTHAN) | (1L << GREATERTHAN_E) | (1L << LESSTHAN_E) | (1L << EQUALS))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalExprOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(ArcherParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(ArcherParser.OR, 0); }
		public LogicalExprOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExprOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterLogicalExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitLogicalExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalExprOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalExprOpContext logicalExprOp() {
		LogicalExprOpContext _localctx = new LogicalExprOpContext(Context, State);
		EnterRule(_localctx, 24, RULE_logicalExprOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201;
			_la = TokenStream.LA(1);
			if ( !(_la==AND || _la==OR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(ArcherParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(ArcherParser.ID, i);
		}
		public PropExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterPropExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitPropExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropExprContext propExpr() {
		PropExprContext _localctx = new PropExprContext(Context, State);
		EnterRule(_localctx, 26, RULE_propExpr);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 203;
			Match(ID);
			State = 208;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 204;
					Match(T__21);
					State = 205;
					Match(ID);
					}
					} 
				}
				State = 210;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ObjContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_obj; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterObj(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitObj(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObj(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjContext obj() {
		ObjContext _localctx = new ObjContext(Context, State);
		EnterRule(_localctx, 28, RULE_obj);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 211;
			Match(T__2);
			State = 215;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==MODIFIER || _la==KEY) {
				{
				{
				State = 212;
				pair();
				}
				}
				State = 217;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 218;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(ArcherParser.KEY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MODIFIER() { return GetToken(ArcherParser.MODIFIER, 0); }
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterPair(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitPair(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPair(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 30, RULE_pair);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 221;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MODIFIER) {
				{
				State = 220;
				Match(MODIFIER);
				}
			}

			State = 223;
			Match(KEY);
			State = 224;
			Match(T__7);
			State = 225;
			value();
			State = 226;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PrimitiveValueContext primitiveValue() {
			return GetRuleContext<PrimitiveValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjContext obj() {
			return GetRuleContext<ObjContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayContext array() {
			return GetRuleContext<ArrayContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 32, RULE_value);
		try {
			State = 231;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
			case NUMBER:
			case BOOLEAN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 228;
				primitiveValue();
				}
				break;
			case T__2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 229;
				obj();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 3);
				{
				State = 230;
				array();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimitiveValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(ArcherParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(ArcherParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(ArcherParser.BOOLEAN, 0); }
		public PrimitiveValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primitiveValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterPrimitiveValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitPrimitiveValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrimitiveValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimitiveValueContext primitiveValue() {
		PrimitiveValueContext _localctx = new PrimitiveValueContext(Context, State);
		EnterRule(_localctx, 34, RULE_primitiveValue);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 233;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << NUMBER) | (1L << BOOLEAN))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayContext array() {
		ArrayContext _localctx = new ArrayContext(Context, State);
		EnterRule(_localctx, 36, RULE_array);
		int _la;
		try {
			State = 248;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,28,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 235;
				Match(T__22);
				State = 236;
				value();
				State = 241;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__12) {
					{
					{
					State = 237;
					Match(T__12);
					State = 238;
					value();
					}
					}
					State = 243;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 244;
				Match(T__23);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 246;
				Match(T__22);
				State = 247;
				Match(T__23);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ListComprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ArcherParser.ID, 0); }
		public ListComprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_listCompr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.EnterListCompr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IArcherListener typedListener = listener as IArcherListener;
			if (typedListener != null) typedListener.ExitListCompr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArcherVisitor<TResult> typedVisitor = visitor as IArcherVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListCompr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ListComprContext listCompr() {
		ListComprContext _localctx = new ListComprContext(Context, State);
		EnterRule(_localctx, 38, RULE_listCompr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250;
			Match(T__2);
			State = 251;
			expr(0);
			State = 252;
			Match(T__24);
			State = 253;
			Match(ID);
			State = 254;
			Match(T__25);
			State = 255;
			expr(0);
			State = 256;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 6: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 8);
		case 1: return Precpred(Context, 7);
		case 2: return Precpred(Context, 5);
		case 3: return Precpred(Context, 4);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,45,259,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,1,0,1,0,3,0,43,8,0,4,
		0,45,8,0,11,0,12,0,46,1,0,1,0,1,1,1,1,1,1,3,1,54,8,1,1,1,1,1,1,1,3,1,59,
		8,1,4,1,61,8,1,11,1,12,1,62,1,1,1,1,1,1,1,1,1,1,1,1,3,1,71,8,1,1,1,1,1,
		1,1,3,1,76,8,1,1,1,3,1,79,8,1,1,1,1,1,3,1,83,8,1,1,1,1,1,1,1,1,1,1,1,3,
		1,90,8,1,1,1,1,1,1,1,1,1,3,1,96,8,1,1,1,1,1,1,1,1,1,3,1,102,8,1,1,1,1,
		1,1,1,1,1,1,1,1,1,1,1,5,1,111,8,1,10,1,12,1,114,9,1,3,1,116,8,1,1,1,1,
		1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,127,8,1,1,2,1,2,1,3,1,3,1,4,1,4,1,4,
		5,4,136,8,4,10,4,12,4,139,9,4,1,5,1,5,1,5,1,5,5,5,145,8,5,10,5,12,5,148,
		9,5,1,6,1,6,1,6,1,6,3,6,154,8,6,1,6,1,6,3,6,158,8,6,1,6,1,6,1,6,1,6,1,
		6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,5,6,176,8,6,10,6,12,6,179,
		9,6,1,7,1,7,1,7,1,7,3,7,185,8,7,1,7,1,7,1,8,1,8,1,8,3,8,192,8,8,1,8,1,
		8,1,9,1,9,1,10,1,10,1,11,1,11,1,12,1,12,1,13,1,13,1,13,5,13,207,8,13,10,
		13,12,13,210,9,13,1,14,1,14,5,14,214,8,14,10,14,12,14,217,9,14,1,14,1,
		14,1,15,3,15,222,8,15,1,15,1,15,1,15,1,15,1,15,1,16,1,16,1,16,3,16,232,
		8,16,1,17,1,17,1,18,1,18,1,18,1,18,5,18,240,8,18,10,18,12,18,243,9,18,
		1,18,1,18,1,18,1,18,3,18,249,8,18,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,
		19,1,19,0,1,12,20,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,
		38,0,7,1,0,17,18,1,0,19,20,1,0,34,35,1,0,36,37,1,0,38,42,1,0,43,44,1,0,
		28,30,281,0,44,1,0,0,0,2,126,1,0,0,0,4,128,1,0,0,0,6,130,1,0,0,0,8,132,
		1,0,0,0,10,140,1,0,0,0,12,157,1,0,0,0,14,180,1,0,0,0,16,188,1,0,0,0,18,
		195,1,0,0,0,20,197,1,0,0,0,22,199,1,0,0,0,24,201,1,0,0,0,26,203,1,0,0,
		0,28,211,1,0,0,0,30,221,1,0,0,0,32,231,1,0,0,0,34,233,1,0,0,0,36,248,1,
		0,0,0,38,250,1,0,0,0,40,42,3,2,1,0,41,43,5,1,0,0,42,41,1,0,0,0,42,43,1,
		0,0,0,43,45,1,0,0,0,44,40,1,0,0,0,45,46,1,0,0,0,46,44,1,0,0,0,46,47,1,
		0,0,0,47,48,1,0,0,0,48,49,5,0,0,1,49,1,1,0,0,0,50,51,5,2,0,0,51,53,5,27,
		0,0,52,54,3,10,5,0,53,52,1,0,0,0,53,54,1,0,0,0,54,55,1,0,0,0,55,60,5,3,
		0,0,56,58,3,2,1,0,57,59,5,1,0,0,58,57,1,0,0,0,58,59,1,0,0,0,59,61,1,0,
		0,0,60,56,1,0,0,0,61,62,1,0,0,0,62,60,1,0,0,0,62,63,1,0,0,0,63,64,1,0,
		0,0,64,65,5,4,0,0,65,127,1,0,0,0,66,67,5,27,0,0,67,68,5,36,0,0,68,70,5,
		33,0,0,69,71,3,14,7,0,70,69,1,0,0,0,70,71,1,0,0,0,71,72,1,0,0,0,72,73,
		5,5,0,0,73,75,5,27,0,0,74,76,3,28,14,0,75,74,1,0,0,0,75,76,1,0,0,0,76,
		127,1,0,0,0,77,79,3,4,2,0,78,77,1,0,0,0,78,79,1,0,0,0,79,80,1,0,0,0,80,
		82,5,27,0,0,81,83,3,28,14,0,82,81,1,0,0,0,82,83,1,0,0,0,83,127,1,0,0,0,
		84,85,5,6,0,0,85,127,3,12,6,0,86,87,5,7,0,0,87,89,5,27,0,0,88,90,5,8,0,
		0,89,88,1,0,0,0,89,90,1,0,0,0,90,91,1,0,0,0,91,127,3,12,6,0,92,93,5,9,
		0,0,93,95,5,27,0,0,94,96,5,8,0,0,95,94,1,0,0,0,95,96,1,0,0,0,96,97,1,0,
		0,0,97,127,3,12,6,0,98,99,5,10,0,0,99,101,5,27,0,0,100,102,5,8,0,0,101,
		100,1,0,0,0,101,102,1,0,0,0,102,103,1,0,0,0,103,127,3,12,6,0,104,105,5,
		11,0,0,105,106,5,33,0,0,106,115,5,12,0,0,107,112,5,33,0,0,108,109,5,13,
		0,0,109,111,5,33,0,0,110,108,1,0,0,0,111,114,1,0,0,0,112,110,1,0,0,0,112,
		113,1,0,0,0,113,116,1,0,0,0,114,112,1,0,0,0,115,107,1,0,0,0,115,116,1,
		0,0,0,116,117,1,0,0,0,117,118,5,14,0,0,118,119,5,15,0,0,119,127,3,12,6,
		0,120,121,5,16,0,0,121,127,5,28,0,0,122,123,3,6,3,0,123,124,3,12,6,0,124,
		127,1,0,0,0,125,127,5,31,0,0,126,50,1,0,0,0,126,66,1,0,0,0,126,78,1,0,
		0,0,126,84,1,0,0,0,126,86,1,0,0,0,126,92,1,0,0,0,126,98,1,0,0,0,126,104,
		1,0,0,0,126,120,1,0,0,0,126,122,1,0,0,0,126,125,1,0,0,0,127,3,1,0,0,0,
		128,129,7,0,0,0,129,5,1,0,0,0,130,131,7,1,0,0,131,7,1,0,0,0,132,137,3,
		12,6,0,133,134,5,13,0,0,134,136,3,12,6,0,135,133,1,0,0,0,136,139,1,0,0,
		0,137,135,1,0,0,0,137,138,1,0,0,0,138,9,1,0,0,0,139,137,1,0,0,0,140,141,
		5,21,0,0,141,146,5,27,0,0,142,143,5,13,0,0,143,145,5,27,0,0,144,142,1,
		0,0,0,145,148,1,0,0,0,146,144,1,0,0,0,146,147,1,0,0,0,147,11,1,0,0,0,148,
		146,1,0,0,0,149,150,6,6,-1,0,150,158,5,33,0,0,151,154,3,26,13,0,152,154,
		3,32,16,0,153,151,1,0,0,0,153,152,1,0,0,0,154,158,1,0,0,0,155,158,3,16,
		8,0,156,158,3,38,19,0,157,149,1,0,0,0,157,153,1,0,0,0,157,155,1,0,0,0,
		157,156,1,0,0,0,158,177,1,0,0,0,159,160,10,8,0,0,160,161,3,18,9,0,161,
		162,3,12,6,9,162,176,1,0,0,0,163,164,10,7,0,0,164,165,3,20,10,0,165,166,
		3,12,6,8,166,176,1,0,0,0,167,168,10,5,0,0,168,169,3,22,11,0,169,170,3,
		12,6,6,170,176,1,0,0,0,171,172,10,4,0,0,172,173,3,24,12,0,173,174,3,12,
		6,5,174,176,1,0,0,0,175,159,1,0,0,0,175,163,1,0,0,0,175,167,1,0,0,0,175,
		171,1,0,0,0,176,179,1,0,0,0,177,175,1,0,0,0,177,178,1,0,0,0,178,13,1,0,
		0,0,179,177,1,0,0,0,180,181,5,12,0,0,181,182,5,29,0,0,182,184,5,13,0,0,
		183,185,5,29,0,0,184,183,1,0,0,0,184,185,1,0,0,0,185,186,1,0,0,0,186,187,
		5,14,0,0,187,15,1,0,0,0,188,189,5,33,0,0,189,191,5,12,0,0,190,192,3,8,
		4,0,191,190,1,0,0,0,191,192,1,0,0,0,192,193,1,0,0,0,193,194,5,14,0,0,194,
		17,1,0,0,0,195,196,7,2,0,0,196,19,1,0,0,0,197,198,7,3,0,0,198,21,1,0,0,
		0,199,200,7,4,0,0,200,23,1,0,0,0,201,202,7,5,0,0,202,25,1,0,0,0,203,208,
		5,27,0,0,204,205,5,22,0,0,205,207,5,27,0,0,206,204,1,0,0,0,207,210,1,0,
		0,0,208,206,1,0,0,0,208,209,1,0,0,0,209,27,1,0,0,0,210,208,1,0,0,0,211,
		215,5,3,0,0,212,214,3,30,15,0,213,212,1,0,0,0,214,217,1,0,0,0,215,213,
		1,0,0,0,215,216,1,0,0,0,216,218,1,0,0,0,217,215,1,0,0,0,218,219,5,4,0,
		0,219,29,1,0,0,0,220,222,5,32,0,0,221,220,1,0,0,0,221,222,1,0,0,0,222,
		223,1,0,0,0,223,224,5,33,0,0,224,225,5,8,0,0,225,226,3,32,16,0,226,227,
		5,1,0,0,227,31,1,0,0,0,228,232,3,34,17,0,229,232,3,28,14,0,230,232,3,36,
		18,0,231,228,1,0,0,0,231,229,1,0,0,0,231,230,1,0,0,0,232,33,1,0,0,0,233,
		234,7,6,0,0,234,35,1,0,0,0,235,236,5,23,0,0,236,241,3,32,16,0,237,238,
		5,13,0,0,238,240,3,32,16,0,239,237,1,0,0,0,240,243,1,0,0,0,241,239,1,0,
		0,0,241,242,1,0,0,0,242,244,1,0,0,0,243,241,1,0,0,0,244,245,5,24,0,0,245,
		249,1,0,0,0,246,247,5,23,0,0,247,249,5,24,0,0,248,235,1,0,0,0,248,246,
		1,0,0,0,249,37,1,0,0,0,250,251,5,3,0,0,251,252,3,12,6,0,252,253,5,25,0,
		0,253,254,5,27,0,0,254,255,5,26,0,0,255,256,3,12,6,0,256,257,5,4,0,0,257,
		39,1,0,0,0,29,42,46,53,58,62,70,75,78,82,89,95,101,112,115,126,137,146,
		153,157,175,177,184,191,208,215,221,231,241,248
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
