//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Archer.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ArcherParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IArcherListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] ArcherParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] ArcherParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>modelStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelStatement([NotNull] ArcherParser.ModelStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>modelStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelStatement([NotNull] ArcherParser.ModelStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>relationshipStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationshipStatement([NotNull] ArcherParser.RelationshipStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>relationshipStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationshipStatement([NotNull] ArcherParser.RelationshipStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>variableDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarationStatement([NotNull] ArcherParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>variableDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarationStatement([NotNull] ArcherParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>constraintStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraintStatement([NotNull] ArcherParser.ConstraintStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>constraintStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraintStatement([NotNull] ArcherParser.ConstraintStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>conditionStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionStatement([NotNull] ArcherParser.ConditionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>conditionStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionStatement([NotNull] ArcherParser.ConditionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lowerBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLowerBoundStatement([NotNull] ArcherParser.LowerBoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lowerBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLowerBoundStatement([NotNull] ArcherParser.LowerBoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>upperBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpperBoundStatement([NotNull] ArcherParser.UpperBoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>upperBoundStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpperBoundStatement([NotNull] ArcherParser.UpperBoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDeclarationStatement([NotNull] ArcherParser.FuncDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcDeclarationStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDeclarationStatement([NotNull] ArcherParser.FuncDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>includeStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeStatement([NotNull] ArcherParser.IncludeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>includeStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeStatement([NotNull] ArcherParser.IncludeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>objectiveStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectiveStatement([NotNull] ArcherParser.ObjectiveStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>objectiveStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectiveStatement([NotNull] ArcherParser.ObjectiveStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>commentStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentStatement([NotNull] ArcherParser.CommentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>commentStatement</c>
	/// labeled alternative in <see cref="ArcherParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentStatement([NotNull] ArcherParser.CommentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.typeDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclr([NotNull] ArcherParser.TypeDeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.typeDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclr([NotNull] ArcherParser.TypeDeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.objectiveDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectiveDeclr([NotNull] ArcherParser.ObjectiveDeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.objectiveDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectiveDeclr([NotNull] ArcherParser.ObjectiveDeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] ArcherParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] ArcherParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdList([NotNull] ArcherParser.IdListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdList([NotNull] ArcherParser.IdListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcArgExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncArgExpr([NotNull] ArcherParser.FuncArgExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcArgExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncArgExpr([NotNull] ArcherParser.FuncArgExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueExpr([NotNull] ArcherParser.ValueExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueExpr([NotNull] ArcherParser.ValueExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExpr([NotNull] ArcherParser.AddSubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExpr([NotNull] ArcherParser.AddSubExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>listComprExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListComprExpr([NotNull] ArcherParser.ListComprExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>listComprExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListComprExpr([NotNull] ArcherParser.ListComprExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCallExpr([NotNull] ArcherParser.FuncCallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCallExpr([NotNull] ArcherParser.FuncCallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>mulDivExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivExpr([NotNull] ArcherParser.MulDivExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mulDivExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivExpr([NotNull] ArcherParser.MulDivExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>equalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualBinaryExpr([NotNull] ArcherParser.EqualBinaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>equalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualBinaryExpr([NotNull] ArcherParser.EqualBinaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>logicalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalBinaryExpr([NotNull] ArcherParser.LogicalBinaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>logicalBinaryExpr</c>
	/// labeled alternative in <see cref="ArcherParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalBinaryExpr([NotNull] ArcherParser.LogicalBinaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.cardinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCardinExpr([NotNull] ArcherParser.CardinExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.cardinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCardinExpr([NotNull] ArcherParser.CardinExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] ArcherParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] ArcherParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.mulDivExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivExprOp([NotNull] ArcherParser.MulDivExprOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.mulDivExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivExprOp([NotNull] ArcherParser.MulDivExprOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.addSubExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExprOp([NotNull] ArcherParser.AddSubExprOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.addSubExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExprOp([NotNull] ArcherParser.AddSubExprOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.equalExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualExprOp([NotNull] ArcherParser.EqualExprOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.equalExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualExprOp([NotNull] ArcherParser.EqualExprOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.logicalExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExprOp([NotNull] ArcherParser.LogicalExprOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.logicalExprOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExprOp([NotNull] ArcherParser.LogicalExprOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.propExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropExpr([NotNull] ArcherParser.PropExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.propExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropExpr([NotNull] ArcherParser.PropExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj([NotNull] ArcherParser.ObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj([NotNull] ArcherParser.ObjContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] ArcherParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] ArcherParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ArcherParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ArcherParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.primitiveValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveValue([NotNull] ArcherParser.PrimitiveValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.primitiveValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveValue([NotNull] ArcherParser.PrimitiveValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] ArcherParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] ArcherParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArcherParser.listCompr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListCompr([NotNull] ArcherParser.ListComprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArcherParser.listCompr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListCompr([NotNull] ArcherParser.ListComprContext context);
}
