<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Configurations>Debug;Release;</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Antlr4.Runtime.Standard" Version="4.10.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Lang\" />
    </ItemGroup>

</Project>
