//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from z3proof.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="z3proofParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface Iz3proofListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.z3proof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZ3proof([NotNull] z3proofParser.Z3proofContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.z3proof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZ3proof([NotNull] z3proofParser.Z3proofContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] z3proofParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] z3proofParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.letExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetExpr([NotNull] z3proofParser.LetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.letExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetExpr([NotNull] z3proofParser.LetExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.assertExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertExpr([NotNull] z3proofParser.AssertExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.assertExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertExpr([NotNull] z3proofParser.AssertExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] z3proofParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] z3proofParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.equalsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualsExpr([NotNull] z3proofParser.EqualsExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.equalsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualsExpr([NotNull] z3proofParser.EqualsExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.unitResolutionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitResolutionExpr([NotNull] z3proofParser.UnitResolutionExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.unitResolutionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitResolutionExpr([NotNull] z3proofParser.UnitResolutionExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.mpExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMpExpr([NotNull] z3proofParser.MpExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.mpExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMpExpr([NotNull] z3proofParser.MpExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.rewriteExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewriteExpr([NotNull] z3proofParser.RewriteExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.rewriteExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewriteExpr([NotNull] z3proofParser.RewriteExprContext context);
}
