//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from z3proof.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="z3proofParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface Iz3proofListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] z3proofParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] z3proofParser.ParseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] z3proofParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] z3proofParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.let"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLet([NotNull] z3proofParser.LetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.let"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLet([NotNull] z3proofParser.LetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinding([NotNull] z3proofParser.BindingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinding([NotNull] z3proofParser.BindingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.asserted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsserted([NotNull] z3proofParser.AssertedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.asserted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsserted([NotNull] z3proofParser.AssertedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.rewrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewrite([NotNull] z3proofParser.RewriteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.rewrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewrite([NotNull] z3proofParser.RewriteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] z3proofParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] z3proofParser.FuncCallContext context);
}
