//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from z3proof.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Iz3proofListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class z3proofBaseListener : Iz3proofListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] z3proofParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] z3proofParser.ParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] z3proofParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] z3proofParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.letExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetExpr([NotNull] z3proofParser.LetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.letExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetExpr([NotNull] z3proofParser.LetExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.bindings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindings([NotNull] z3proofParser.BindingsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.bindings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindings([NotNull] z3proofParser.BindingsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.binding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinding([NotNull] z3proofParser.BindingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.binding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinding([NotNull] z3proofParser.BindingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.mpExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMpExpr([NotNull] z3proofParser.MpExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.mpExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMpExpr([NotNull] z3proofParser.MpExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.assertedExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssertedExpr([NotNull] z3proofParser.AssertedExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.assertedExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssertedExpr([NotNull] z3proofParser.AssertedExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.rewriteExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRewriteExpr([NotNull] z3proofParser.RewriteExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.rewriteExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRewriteExpr([NotNull] z3proofParser.RewriteExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] z3proofParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] z3proofParser.FuncCallContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
