//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from z3proof.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="z3proofParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface Iz3proofListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] z3proofParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] z3proofParser.ParseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] z3proofParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] z3proofParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.letExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetExpr([NotNull] z3proofParser.LetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.letExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetExpr([NotNull] z3proofParser.LetExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.bindings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBindings([NotNull] z3proofParser.BindingsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.bindings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBindings([NotNull] z3proofParser.BindingsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinding([NotNull] z3proofParser.BindingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinding([NotNull] z3proofParser.BindingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.mpExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMpExpr([NotNull] z3proofParser.MpExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.mpExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMpExpr([NotNull] z3proofParser.MpExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.assertedExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertedExpr([NotNull] z3proofParser.AssertedExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.assertedExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertedExpr([NotNull] z3proofParser.AssertedExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.rewriteExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewriteExpr([NotNull] z3proofParser.RewriteExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.rewriteExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewriteExpr([NotNull] z3proofParser.RewriteExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="z3proofParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] z3proofParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="z3proofParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] z3proofParser.FuncCallContext context);
}
