//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from z3proof.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public partial class z3proofLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, ID=12, WS=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "ID", "WS"
	};


	public z3proofLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public z3proofLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'(let'", "'@'", "'(asserted'", "'not'", "'= a b'", 
		"'unit-resolution'", "'mp'", "'rewrite'", "'= expr expr'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "z3proof.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static z3proofLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,13,112,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,1,0,1,0,1,1,1,
		1,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,
		1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,
		7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,
		1,9,1,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,
		11,3,11,99,8,11,1,11,4,11,102,8,11,11,11,12,11,103,1,12,4,12,107,8,12,
		11,12,12,12,108,1,12,1,12,0,0,13,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,
		9,19,10,21,11,23,12,25,13,1,0,2,3,0,48,57,65,90,97,122,3,0,9,10,13,13,
		32,32,114,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,
		0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,
		1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,1,27,1,0,0,0,3,29,1,0,0,0,5,31,1,0,0,
		0,7,36,1,0,0,0,9,38,1,0,0,0,11,48,1,0,0,0,13,52,1,0,0,0,15,58,1,0,0,0,
		17,74,1,0,0,0,19,77,1,0,0,0,21,85,1,0,0,0,23,98,1,0,0,0,25,106,1,0,0,0,
		27,28,5,40,0,0,28,2,1,0,0,0,29,30,5,41,0,0,30,4,1,0,0,0,31,32,5,40,0,0,
		32,33,5,108,0,0,33,34,5,101,0,0,34,35,5,116,0,0,35,6,1,0,0,0,36,37,5,64,
		0,0,37,8,1,0,0,0,38,39,5,40,0,0,39,40,5,97,0,0,40,41,5,115,0,0,41,42,5,
		115,0,0,42,43,5,101,0,0,43,44,5,114,0,0,44,45,5,116,0,0,45,46,5,101,0,
		0,46,47,5,100,0,0,47,10,1,0,0,0,48,49,5,110,0,0,49,50,5,111,0,0,50,51,
		5,116,0,0,51,12,1,0,0,0,52,53,5,61,0,0,53,54,5,32,0,0,54,55,5,97,0,0,55,
		56,5,32,0,0,56,57,5,98,0,0,57,14,1,0,0,0,58,59,5,117,0,0,59,60,5,110,0,
		0,60,61,5,105,0,0,61,62,5,116,0,0,62,63,5,45,0,0,63,64,5,114,0,0,64,65,
		5,101,0,0,65,66,5,115,0,0,66,67,5,111,0,0,67,68,5,108,0,0,68,69,5,117,
		0,0,69,70,5,116,0,0,70,71,5,105,0,0,71,72,5,111,0,0,72,73,5,110,0,0,73,
		16,1,0,0,0,74,75,5,109,0,0,75,76,5,112,0,0,76,18,1,0,0,0,77,78,5,114,0,
		0,78,79,5,101,0,0,79,80,5,119,0,0,80,81,5,114,0,0,81,82,5,105,0,0,82,83,
		5,116,0,0,83,84,5,101,0,0,84,20,1,0,0,0,85,86,5,61,0,0,86,87,5,32,0,0,
		87,88,5,101,0,0,88,89,5,120,0,0,89,90,5,112,0,0,90,91,5,114,0,0,91,92,
		5,32,0,0,92,93,5,101,0,0,93,94,5,120,0,0,94,95,5,112,0,0,95,96,5,114,0,
		0,96,22,1,0,0,0,97,99,5,36,0,0,98,97,1,0,0,0,98,99,1,0,0,0,99,101,1,0,
		0,0,100,102,7,0,0,0,101,100,1,0,0,0,102,103,1,0,0,0,103,101,1,0,0,0,103,
		104,1,0,0,0,104,24,1,0,0,0,105,107,7,1,0,0,106,105,1,0,0,0,107,108,1,0,
		0,0,108,106,1,0,0,0,108,109,1,0,0,0,109,110,1,0,0,0,110,111,6,12,0,0,111,
		26,1,0,0,0,4,0,98,103,108,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
