export class BrokenModels {
    public static models: string[] =  [

/* Model 1 */
      "model [Phone] { \n"
      + "    [Phone] - mandatory -> [Screen] \n"
      + "    [Screen] - excludes -> [Screen] \n"
      + "}",

/* Model 2 */
      "model [Phone] { \n"
      + "    [Phone] - mandatory -> [Screen] \n"
      + "    [Phone] - mandatory -> [FingerPrint] \n"
      + "    [FingerPrint] - requires -> [Screen] \n"
      + "    [Screen] - excludes -> [FingerPrint] \n"
      + "}",

/* Model 3 */
      "model [Phone] { \n"
      + "    [Phone] - mandatory -> [Screen] \n"
      + "    [Phone] - mandatory -> [FingerPrint] \n"
      + "    [Phone] - alternative -> [GPS] \n"
      + "    [Phone] - alternative -> [Media] \n"
      + "    [Screen] - excludes -> [GPS] \n"
      + "    [FingerPrint] - excludes -> [Media] \n"
      + "}",

/* Model 4 */
      "model [Root] { \n"
      + "    [Root] - optional -> [Gravity] \n"
      + "    [Root] - mandatory -> [Screws] \n"
      + "    [Root] - mandatory -> [Distance] \n"

      + "    [Root] - alternative -> [Height] \n"
      + "    [Root] - alternative -> [Width] \n"
      + "    [Root] - alternative -> [Depth] \n"
      + "    [Root] - alternative -> [Scale] \n"
      
      + "    [Height] - requires -> [Gravity] \n"
      + "    [Distance] - excludes -> [Screws] \n"
      + "    [Gravity] - requires -> [Depth] \n"
      + "    [Screws] - excludes -> [Distance] \n"
      + "}",

/* Model 5 */
      "model [Root] { \n"
      + "    [Root] - mandatory -> [Calculation] \n"
      + "    [Root] - mandatory -> [Price] \n"
      + "    [Root] - mandatory -> [Estimations] \n"
      + "\n"
      + "    [Calculation] - mandatory -> [Distance] \n"
      + "    [Calculation] - mandatory -> [Height] \n"
      + "    [Calculation] - or -> [Width] \n"
      + "    [Calculation] - or -> [Length] \n"
      + "\n"
      + "    [Distance] - alternative -> [Miles] \n"
      + "    [Distance] - alternative -> [Kilometers] \n"
      + "    [Distance] - mandatory -> [Value] \n"
      + "    [Distance] - optional -> [ErrorMargin] \n"
      + "\n"
      + "    [Price] - mandatory -> [BillOfMaterial] \n"
      + "    [Price] - mandatory -> [CostOverview] \n"
      + "    [Price] - optional -> [Invoice] \n"
      + "    [Price] - mandatory -> [HoursWorked] \n"
      + "\n"
      + "    [Value] - excludes -> [CostOverview] \n"
      + "}",

/* Model 6 */
      "model [Phone] { \n"
      + "    [Phone] - mandatory -> [Screen] \n"
      + "    [Phone] - mandatory -> [Finger Print] \n"
      + "    [Phone] - alternative -> [alt1] \n"
      + "    [Phone] - alternative -> [alt2] \n"
      + "\n"
      + "    [alt1] - alternative -> [alt11] \n"
      + "    [alt1] - alternative -> [alt12] \n"
      + "    [alt1] - alternative -> [alt13] \n"
      + "    [alt1] - alternative -> [alt14] \n"
      + "\n"
      + "    [alt2] - alternative -> [alt21] \n"
      + "    [alt2] - alternative -> [alt22] \n"
      + "    [alt2] - alternative -> [alt23] \n"
      + "    [alt2] - alternative -> [alt24] \n"
      + "\n"
      + "    [alt12] - alternative -> [alt121] \n"
      + "    [alt12] - alternative -> [alt122] \n"
      + "\n"
      + "    [alt2] - requires-> [alt1]  \n"
      + "    [alt1] - requires-> [alt2]  \n"
      + "}",

/* Model 7 */
      "model [Phone] { \n"
	+ "    [Phone] - mandatory -> [Calls] \n"
	+ "    [Phone] - optional -> [GPS] \n"
      + "\n"    
	+ "    [Phone] - mandatory -> [Warranty] \n"
	+ "    [Warranty] - mandatory -> [FullCoverage] \n"
      + "\n"    
	+ "    [Phone] - mandatory -> [Screen] \n"
	+ "    [Screen] - alternative -> [Basic] \n"
	+ "    [Screen] - alternative -> [Color] \n"
	+ "    [Screen] - alternative -> [HD] \n"
      + "\n"
	+ "    [Color] - mandatory -> [RGB] \n"
	+ "    [Calls] - mandatory -> [Wifi] \n"
      + "\n"
	+ "    [Phone] - optional -> [Media] \n"
	+ "    [Media] - or -> [Camera] \n"
	+ "    [Media] - or -> [MP3] \n"
      + "\n"
	+ "    [Camera] - requires -> [HD] \n"
	+ "    [GPS] - excludes -> [Basic] \n"
	+ "    [Wifi] - excludes -> [FullCoverage] \n"
      + "}",

/* Model 8 */
      "model [Phone] { \n"
	+ "    [Media] - or -> [MP3] \n"
	+ "    [Phone] - mandatory -> [Screen] \n"
	+ "    [Screen] - alternative -> [Basic] \n"
	+ "    [Color] - mandatory -> [RGB] \n"
	+ "    [Calls] - mandatory -> [Wifi] \n"
	+ "    [Phone] - mandatory -> [Calls] \n"
	+ "    [Phone] - optional -> [GPS] \n"
	+ "    [Phone] - mandatory -> [Warranty] \n"
	+ "    [Warranty] - mandatory -> [FullCoverage] \n"
	+ "    [Screen] - alternative -> [Color] \n"
	+ "    [Camera] - requires -> [HD] \n"
	+ "    [Screen] - alternative -> [HD] \n"
	+ "    [GPS] - excludes -> [Basic] \n"
	+ "    [Phone] - optional -> [Media] \n"
	+ "    [Media] - or -> [Camera] \n"
	+ "    [Wifi] - excludes -> [FullCoverage] \n"
      + "}",



/* Model 9 */
      "model [Phone] {  \n"
      + "    [Phone] - mandatory -> [Screen]   \n"
      + "    [Phone] - mandatory -> [FingerPrint]   \n"
      + "    [Phone] - alternative -> [Bluetooth]  \n" 
      + "    [Phone] - alternative -> [GPS]   \n"
      + "\n"
      + "    [Bluetooth] - alternative -> [V5]   \n"
      + "    [Bluetooth] - alternative -> [V4]   \n"
      + "    [Bluetooth] - alternative -> [V3]   \n"
      + "    [Bluetooth] - alternative -> [V2]   \n"
      + "    [Bluetooth] - alternative -> [V1]   \n"
      + "\n"
      + "    [GPS] - alternative -> [Locally]   \n"
      + "    [GPS] - alternative -> [NationWide]   \n"
      + "    [GPS] - alternative -> [Continental]   \n"
      + "    [GPS] - alternative -> [WorldWide]   \n"
      + "\n"
      + "    [V1] - requires-> [WiFi]    \n"
      + "    [Locally] - requires-> [V2]    \n"
      + "    [V3] - requires-> [NationWide]    \n"
      + "    [Bluetooth] - requires-> [GPS]    \n"
      + "    [Continental] - requires-> [V4]    \n"
      + "    [V5] - requires-> [WorldWide]    \n"
      + "    [GPS] - requires-> [Bluetooth]  \n"
      + "}",

/* Model 10 */
      "model [Phone] {  \n"
      + "    [Phone] - mandatory -> [Screen]   \n"
      + "    [Phone] - mandatory -> [FingerPrint]   \n"
      + "    [Phone] - optional -> [WiFi]   \n"
      + "    [Phone] - alternative -> [Bluetooth]  \n" 
      + "    [Phone] - alternative -> [GPS]   \n"
      + "    [Phone] - optional -> [Antenna]   \n"
      + "\n"
      + "    [Bluetooth] - alternative -> [V5]   \n"
      + "    [Bluetooth] - alternative -> [V4]   \n"
      + "    [Bluetooth] - alternative -> [V3]   \n"
      + "    [Bluetooth] - alternative -> [V2]   \n"
      + "    [Bluetooth] - alternative -> [V1]   \n"
      + "\n"
      + "    [V1] - requires-> [WiFi]    \n"
      + "    [V2] - requires-> [Locally]    \n"
      + "    [V3] - requires-> [NationWide]    \n"
      + "    [V4] - requires-> [Continental]    \n"
      + "    [V5] - requires-> [WorldWide]    \n"
      + "\n"
      + "    [GPS] - alternative -> [Locally]   \n"
      + "    [GPS] - alternative -> [NationWide]   \n"
      + "    [GPS] - alternative -> [Continental]   \n"
      + "    [GPS] - alternative -> [WorldWide]   \n"
      + "\n"
      + "    [WiFi] - Excludes-> [GPS]  \n"
      + "    [Bluetooth] - requires -> [Antenna]  \n"
      + "    [GPS] - requires -> [Antenna]  \n"
      + "    [Antenna] - requires -> [V5]  \n"
      + "    [WorldWide] - requires -> [WiFi]  \n"
      + "}",

    ];
  }